[project]
name = "cxc-hackthon"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "flask>=3.1.2",
    "flask-cors>=6.0.2",
    "matplotlib>=3.10.8",
    "numpy>=2.4.2",
    "onnx>=1.20.1",
    "onnxruntime>=1.24.1",
    "pandas>=3.0.0",
    "torch>=2.10.0",
    "scikit-learn>=1.4.2",
    "onnxscript>=0.6.0",
]
